apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kharcha.fullname" . }}-pricebook
  labels:
    {{- include "kharcha.labels" . | nindent 4 }}
data:
  pricebook.yaml: |
    {{- toYaml .Values.pricebook | nindent 4 }}
