apiVersion: v1
kind: Service
metadata:
  name: {{ include "chidrixx-controlplane.fullname" . }}
  labels:
    {{- include "chidrixx-controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: chidrixx-controlplane
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
